






















































































// 输出图像
const content = `
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOO◆◆◆◆◆◆OOOOOOOOOOO◆◆OOOOOOOO◆◆◆◆OOO◆◆◆OOOOOOOOOOOOOOOOOOOOO◆◆◆◆◆OOOOOOOOOO◆◆◆◆◆◆◆◆◆OOOOOOOOOO◆◆OOOOOOOOO◆◆◆◆◆◆◆OOOOOOOOOOOOOOOOOOOOOOOOO◆◆◆◆◆◆OOOOOOOOOOO◆◆OOOOOOOO◆◆◆◆OOO◆◆◆OOOOOOOOOOOOOOOOOOOO◆◆◆O◆◆◆O◆◆◆OOOOOOOO◆◆◆◆OOOOOOO◆◆◆◆OOO◆◆◆OOO
OOOO◆◆◆OO◆◆OOOOOOOOOO◆◆◆OOOOOOOOOO◆◆◆OOO◆OOOOOOOOOOOOOOOOOOOOOOOO◆OOOOOOOOOOOOOO◆◆OO◆◆◆OOOOOOOOO◆◆◆OOOOOOOOOOO◆OO◆◆◆OOOOOOOOOOOOOOOOOOOOOOO◆◆◆OO◆◆OOOOOOOOOO◆◆◆OOOOOOOOOO◆◆◆OOO◆OOOOOOOOOOOOOOOOOOOOOO◆◆OO◆◆OO◆◆OOOOOOOOO◆◆OOOOOOOOOO◆◆◆OOO◆OOOO
OOOO◆◆OOOO◆◆OOOOOOOOO◆◆◆OOOOOOOOOO◆◆◆OOO◆OOOOOOOOOOOOOOOOOOOOOOOO◆OOOOOOOOOOOOOO◆OOO◆◆◆OOOOOOOOO◆◆◆OOOOOOOOOOO◆OOO◆◆OOOOOOOOOOOOOOOOOOOOOOO◆◆OOOO◆◆OOOOOOOOO◆◆◆OOOOOOOOOO◆◆◆OOO◆OOOOOOOOOOOOOOOOOOOOOO◆◆OO◆◆OO◆OOOOOOOOOO◆OOOOOOOOOOO◆◆◆OOO◆OOOO
OOOO◆◆OOOOOOOOOOOOOOO◆O◆◆OOOOOOOOO◆O◆◆OO◆OOOOOOOOOOOOOOOOOOOOOOOO◆OOOOOOOOOOOOOO◆OOO◆OOOOOOOOOOO◆O◆◆OOOOOOOOOO◆OOO◆◆OOOOOOOOOOOOOOOOOOOOOOO◆◆OOOOOOOOOOOOOOO◆O◆◆OOOOOOOOO◆O◆◆OO◆OOOOOOOOOOOOOOOOOOOOOO◆◆◆◆◆◆◆◆◆OOOOOOOOOO◆OOOOOOOOOOO◆O◆◆OO◆OOOO
OOO◆◆◆OOOOOOOOOOOOOO◆◆O◆◆OOOOOOOOO◆O◆◆◆O◆OOOOOOOOOOOOOOOOOOOOOOOO◆OOOOOOOOOOOOOO◆◆◆◆◆OOOOOOOOOO◆◆O◆◆OOOOOOOOOO◆OOO◆◆◆OOOOOOOOOOOOOOOOOOOOO◆◆◆OOOOOOOOOOOOOO◆◆O◆◆OOOOOOOOO◆O◆◆◆O◆OOOOOOOOOOOOOOOOOOOOOOO◆◆◆◆◆◆◆◆OOOOOOOOOO◆OOOOOOOOOOO◆O◆◆◆O◆OOOO
OOO◆◆◆OOOOOOOOOOOOOO◆◆◆◆◆◆OOOOOOOO◆OO◆◆◆◆OOOOOOOOOOOOOOOOOOOOOOOO◆OOOOOOOOOOOOOO◆OOO◆OOOOOOOOOO◆◆◆◆◆◆OOOOOOOOO◆OOO◆◆OOOOOOOOOOOOOOOOOOOOOO◆◆◆OOOOOOOOOOOOOO◆◆◆◆◆◆OOOOOOOO◆OO◆◆◆◆OOOOOOOOOOOOOOOOOOOOOOO◆◆◆O◆◆◆OOOOOOOOOOO◆OOOOOOOOOOO◆OO◆◆◆◆OOOO
OOOO◆◆OOOO◆◆OOOOOOO◆◆OOO◆◆OOOOOOOO◆OOO◆◆◆OOOOOOOOOOOOOOOOOOOOOOOO◆OOOO◆◆OOOOOOOO◆OOO◆O◆OOOOOOO◆◆OOO◆◆OOOOOOOOO◆OOO◆◆OOOOOOOOOOOOOOOOOOOOOOO◆◆OOOO◆◆OOOOOOO◆◆OOO◆◆OOOOOOOO◆OOO◆◆◆OOOOOOOOOOOOOOOOOOOOOOO◆◆◆O◆◆◆OOOOOOOOOOO◆OOOOOOOOOOO◆OOO◆◆◆OOOO
OOOO◆◆◆OO◆◆◆OOOOOOO◆◆OOO◆◆OOOOOOOO◆OOOO◆◆OOOOOOOOOOOOOOOOOOOOOOOO◆OOO◆◆◆OOOOOOOO◆◆OOO◆◆OOOOOOO◆◆OOO◆◆OOOOOOOOO◆OO◆◆◆OOOOOOOOOOOOOOOOOOOOOOO◆◆◆OO◆◆◆OOOOOOO◆◆OOO◆◆OOOOOOOO◆OOOO◆◆OOOOOOOOOOOOOOOOOOOOOOOO◆◆OO◆◆OOOOOOOOOOO◆OOOOOOOOOOO◆OOOO◆◆OOOO
OOOOO◆◆◆◆◆◆OOOOOOO◆◆◆OO◆◆◆◆◆OOOOO◆◆◆◆OOO◆OOOOOOOOOOOOOOOOOOOOOO◆◆◆◆◆◆◆◆OOOOOOO◆◆◆◆◆◆◆◆◆OOOOOO◆◆◆OO◆◆◆◆◆OOOOO◆◆◆◆◆◆◆OOOOOOOOOOOOOOOOOOOOOOOOO◆◆◆◆◆◆OOOOOOO◆◆◆OO◆◆◆◆◆OOOOO◆◆◆◆OOO◆OOOOOOOOOOOOOOOOOOOOOOOO◆OOO◆◆OOOOOOOOOO◆◆◆◆OOOOOOOO◆◆◆◆OOO◆OOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`;
// 获取Canvas元素
/* 样式代码 */
let date = new Date()
let a = 'background: #606060; color: #fff; border-radius: 3px 0 0 3px;'
let b = 'background: #1475B2; color: #fff; border-radius: 0 3px 3px 0;'

var styleTitle1 = `
font-size: 20px;
font-weight: 600;
color: rgb(244,167,89);

.custom_url_box .content {max-height: 400px; overflow: auto; margin-bottom: 20px;}
.custom_url_box .content .row {display: flex; padding: 4px 0;}
.custom_url_box .content .header {font-size: 16px; font-weight: 500; color: #3f3f3f; margin-bottom: 10px;}
.custom_url_box .content .item_1 {width: 20%;}
.custom_url_box .content .item_1:hover { cursor:pointer;}
.custom_url_box .content .item_1 .oper_icon:before {
    font-size: 12px;
    transition: all 0.3s ease-out;
    transform: translate(-50%, -50%);
}

.custom_url_box .content .item_1 .oper_icon {
    display: inline-block;
    vertical-align: middle;
    border-radius: 36px;
    background-image: none;
    text-align: center;
    font-size: 12px !important;
    transition: all 0.3s ease-out;
    font-family: "iconfont" !important;
    font-style: normal;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
.custom_url_box .content .item_2 {width: 35%;}
.custom_url_box .content .item_3 {width: 20%;}
.custom_url_box .content .item_4 {width: 10%;text-align: center}
.custom_url_box .content .item_4:hover { cursor:pointer;}
.custom_url_box .content .item_4 .icon_del:before{ /*content: "\e6a6"; */}
.custom_url_box .content .item_4 .oper_icon:before {
    font-size: 12px;
    transition: all 0.3s ease-out;
    transform: translate(-50%, -50%);
}

.custom_url_box .content .checkbox {
    width: 14px;
    height: 14px;
    border: 1px solid #ccdced;
    background-repeat: no-repeat;
    background-position: center;
    display: inline-block;
    vertical-align: top;
    border-radius: 2px;
    text-align: center;
    overflow: hidden;
}

.custom_url_box .content .analysis.choise .checkbox {
    background-image: url(../images/frame/icon_checkbox_checked.png);
    background-color: var(--primaryColor);
    border-color: var(--primaryColor);
}


.custom_url_box .content .item_4  a {
    text-decoration: none;
}

.custom_url_box .content .item_4 .oper_icon {
    display: inline-block;
    vertical-align: middle;
    border-radius: 36px;
    background-image: none;
    text-align: center;
    font-size: 0 !important;
    transition: all 0.3s ease-out;
    position: absolute;
    font-family: "iconfont" !important;
    font-size: 16px;
    font-style: normal;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

.custom_url_box .content .item_5 {width: 10%;text-align: right}
.custom_url_box .content .item_5:hover { cursor:pointer;}
.custom_url_box .content .item_5 .icon_del:before{ /*content: "\e6a6";*/ }
.custom_url_box .content .item_5 .oper_icon:before {
    font-size: 12px;
    transition: all 0.3s ease-out;
    transform: translate(-50%, -50%);
}
`

var styleTitle2 = `
font-style: oblique;
font-size:14px;
color: rgb(244,167,89);
font-weight: 400;
`
var styleContent = `
color: rgb(30,152,255);
`
 
// => 读取配置型(在配置文件里配置这些会变动的网址)

console.log(content);